[package]
name = "bevy-state-consumer"
version = "0.1.0"
edition = "2024"

[workspace]

[features]
default = ["selected"]
selected = ["lgwks_deps/bevy-state"]
probe = []

[dependencies]
lgwks_deps = { path = "../../..", default-features = false }

[[example]]
name = "feature_off"
required-features = ["probe"]
